### ISSUE TITLE
 Viết đặc tả usercase cho project

### ISSUE THREAD

**Issue by VoHongKhang** [VoHongKhang/Nhom10_CCPTPM#17]
- [x] (Quốc Chí ) Ngày 3 Viết Flow-event cho từng use case cho tính năng đăng nhập, đăng xuất

- [x] ( Quốc Chí ) Ngày 4 Viết Flow-event cho từng use case cho tính năng xem bài viết, xem thông tin sản phấm,yêu cầu bản demo.

- [x] (Quốc Chí )Ngày 5 Viết Flow-event cho từng use case cho tính năng  thêm sản phẩm, đăng bài viết

- [x] (Quốc Chí) Ngày 6 Viết Flow-event cho từng use case cho tính năng chăm sóc khách hàng

**Comment by QuocChi76** [comment]
Kết quả đạt được trong ngày 3,4,5,6: https://docs.google.com/document/d/1OtGA9_TZnrY1GgQF9KPutF-D_bFotG4WEUKSd7uQfLk/edit?usp=sharing
