### ISSUE TITLE
Vẽ usercase diagram cho project

### ISSUE THREAD

**Issue by VoHongKhang** [VoHongKhang/Nhom10_CCPTPM#18]
- [x] Ngày 3(ĐỨC ANH): Phân tích và vẽ usercase diagram

**Comment by ducanh1811** [comment]
- Ngày 1:

Trên trang web https://www.talkdesk.com/cloud-contact-center/customer-experience-analytics/ , người dùng có thể tìm thấy các thông tin về sản phẩm và dịch vụ của Talkdesk, đặc biệt là các giải pháp trung tâm liên lạc trên đám mây và phân tích trải nghiệm khách hàng. Cụ thể, trang web này có thể cung cấp cho người dùng những thông tin sau: Giới thiệu về Talkdesk và các giải pháp của công ty. Các tính năng và chức năng của các giải pháp trung tâm liên lạc của Talkdesk. Thông tin về các tính năng phân tích trải nghiệm khách hàng của Talkdesk. Các trường hợp sử dụng và thành công của khách hàng đã sử dụng sản phẩm và dịch vụ của Talkdesk. Bài viết, tài liệu và báo cáo về xu hướng và thức thức của ngành trung tâm liên lạc và trải nghiệm khách hàng. Liên hệ với Talkdesk để được hỗ trợ và tư vấn sản phẩm và dịch vụ của công ty.

**Comment by ducanh1811** [comment]
- Ngày 2: https://docs.google.com/document/d/1AwNlwRj7eN9776FY5kJwsdJsA1GxL1Xp_s-WXlST7Rk/edit
