### ISSUE TITLE
Thiết activity diagram cho project

### ISSUE THREAD

**Issue by VoHongKhang** [VoHongKhang/Nhom10_CCPTPM#20]
- [x] Ngày 7 ( Quốc Chí ): Thiết kế activity diagram cho trang web với tính năng xem sản phẩm + liên hệ admin để yêu cầu bản demo

**Comment by QuocChi76** [comment]
link kết quả: https://docs.google.com/document/d/1OLYt4BWX93B4_e-lNK8Od_IT84hXbG9nPT2wKBserdk/edit?usp=sharing
