### ISSUE TITLE
Thiết kế giao diện phần header

### ISSUE THREAD

**Issue by VoHongKhang** [VoHongKhang/Nhom10_CCPTPM#21]
- [x] Ngày 4 (ĐỨC ANH): Mô phỏng trang phần Header
- [x]  Ngày 5 (ĐỨC ANH): Xây dựng phần Header
- [x] Ngày 6: (ĐỨC ANH) chỉnh sửa UI cho haeder bằng scss
- [x] Ngày 7 (ĐỨC ANH): Hoàn thiện phần header

**Comment by ducanh1811** [comment]
- Ngày 4:
- Thanh Header gồm 3 thành phần:

1. logo: Đây là phần chứa logo của web talkdesk
2. mid: ở đây chứa các đường dẫn đến trang khác gồm product, slution, customer, support, resource, about
3. action: phần chứa các nút như tìm kiếm, trang profile,...

**Comment by ducanh1811** [comment]
- Ngày 5: Xây dựng trang header bằng JS;
`
import styles from "./Header.module.scss";
import { useEffect, useState } from "react";
import classNames from "classnames/bind";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faPersonRifle as user,
  faCircleXmark as close,
  faSpinner as loading,
  faMagnifyingGlass as search
} from "@fortawesome/free-solid-svg-icons";
//import Tippy from "@tippyjs/react/headless";
import images from "../../../../assets/images";

const cx = classNames.bind(styles);
function Header() {
  const [searchResult, setSearchResult] = useState([]);

  useEffect(() => {
    setTimeout(() => {
      setSearchResult([1, 2, 3]);
    }, 0);
  }, []);

  return (
    <header className={cx("wrapper")}>
      <div className={cx("inner")}>
        <div
          className={cx("logo")}
          onClick={() => {
            window.location.href = "/";
          }}
        >
          <img src={images.logo} alt="talkdesk" />
        </div>
        <div
          className={cx("menu")}
          onMouseEnter={() => {
            console.log("Enter");
          }}
        >
          <ul>PRODUCTS</ul>
          <ul>SOLUTIONS</ul>
          <ul>CUSTOMERS</ul>
          <ul>SUPPORT</ul>
          <ul>RESOURCES</ul>
          <ul>ABOUT</ul>
        </div>
        <div className={cx("actions")}>
          <a
            href="https://www.talkdesk.com/login"
            className={cx("login")}
            title="Talkdesk Enterprise Platform Login page"
          >
            {" "}
            <FontAwesomeIcon
              style={{
                fontSize: "20px",
                color: "#5405bd",
                margin: "10px"
              }}
              icon={user}
            />{" "}
          </a>
          <button className={cx("search")} title="Search">
            {" "}
            <FontAwesomeIcon
              style={{
                fontSize: "20px",
                color: "#5405bd",
                margin: "10px"
              }}
              icon={search}
            />{" "}
          </button>
        </div>
      </div>
    </header>
  );
}

export default Header;

`

**Comment by ducanh1811** [comment]
- Ngày 6: Sử dụng các thuộc tính cơ bản của css để xây dựng UI cho header bao gồm: 

1. display,
2. margin,
3.  font size, 
4. font famili,....
- Code:
```
.wrapper {
    --search-border-radius: 92px;
    --right-search-button-width: 52px;
    --top-search-space: 9px;
    --search-button-height: 46px;
    --close-button-right: 0px;
    width: 100%;
    height: var(--header-height, 60px);
    box-shadow: 0px 1px 1px rgb(0 0 0 / 12%);
    display: flex;
    justify-content: center;
}

.inner {
    height: 100%;
    display: flex;
    align-items: center;
    width: var(--layout-width, 1150px);
    justify-content: space-between;

    // background-color: #ccc;
}

.logo {
    // Con chuột hình ngón tay
    &:hover {
        cursor: pointer;
    }
}

.clear {
    position: relative;

    right: var(--close-button-right);
    color: rgba(22, 24, 35, 0.34);
    font-size: 1.45rem;
}
.loading {
    position: relative;
    top: 50%;

    right: calc(var(--close-button-right) + 15px);
    transform: translateY(-50%);

    color: rgba(22, 24, 35, 0.34);
    font-size: 1.45rem;
}

.menu {
    display: flex;
    flex: 1;
    align-items: center;
    justify-content: flex-start;
    margin-left: 70px;
    height: 100%;
    background-color: #fff;

    ul {
        font: 1em sans-serif;
        margin: 20px;
        cursor: pointer;
    }
}

.actions {
    display: flex;
    align-items: center;
    justify-content: flex-end;
    flex: 1;
    height: 100%;
    background-color: #fff;

    .search {
        background-color: #fff;
        cursor: pointer;
    }

    .button {
        background-color: #fff;
        cursor: pointer;
    }
}
```
