### ISSUE TITLE
Thiết kế giao diện phần footer

### ISSUE THREAD

**Issue by VoHongKhang** [VoHongKhang/Nhom10_CCPTPM#22]
- [x] Ngày 7 (ĐỨC ANH): Tìm hiểu, xây dựng bố cục cho phần footer

**Comment by ducanh1811** [comment]
- Ngày 7 (ĐỨC ANH)
- Bố cục của footer chia làm 2 phần:

1.  Content: Chứa đường dẫn đến các opition của trang, ví dụ: 
- Why Talkdesk: Chứa các option như: chăm sóc khách hàng, buôn bán, giá thành, kết nối, ...
- Company: các thông tin liên quan đến công ty, sự kiện, đối tác, quản lý, giám đốc, nhà phát triển,...
- Solution: liên quan đến truyền thông và cộng đồng, sức khỏe, cuộc sống, lĩnh vực về ý tế, giáo dục,....
- Product: các sản phẩm demo, phân tích, đánh giá, cộng tác phát triển,...
- Resource: trang blog, tâm sự, chia sẽ, tài liệu phát triển ...
2.   Connect: Chứa các kênh thông tin liên lạc: twiter, facebook, intagram, ... Chứa các bản quyền, thông tin nhà phát triển,...
