### ISSUE TITLE
Dịch vụ business-intelligence

### ISSUE THREAD

**Issue by VoHongKhang** [VoHongKhang/Nhom10_CCPTPM#25]
- [x] Tìm hiểu và thiết kế UI cho dịch vụ business-intelligence

**Comment by QuocChi76** [comment]
Kết quả đạt được:
Link figma: https://www.figma.com/file/f23uEjUAbk79zr7XbmJeNu/Nh%C3%B3m-10?node-id=1-42&t=y0LiefjyUVAcsKee-0
Mô tả dịch vụ :mục 3.3 tài liệu https://docs.google.com/document/d/1XVHaUNoguIhTs_ZXBmcIV_qowdq4-n4h/edit?rtpof=true&sd=true
