### ISSUE TITLE
System Features và External Interface Requirements

### ISSUE THREAD

**Issue by VoHongKhang** [VoHongKhang/Nhom10_CCPTPM#29]
- [x] System features cho dịch vụ business-intelligence
- [x] System features cho dịch vụ feedback
- [x] System features cho dịch vụ  real-time-dashboards
- [x] System features cho dịch vụ interaction-analytics-sentiment
- [x] External Interface Requirements

**Comment by QuocChi76** [comment]
Kết quả của các task: https://docs.google.com/document/d/1XVHaUNoguIhTs_ZXBmcIV_qowdq4-n4h/edit?rtpof=true&sd=true
