### ISSUE TITLE
Other Nonfunctional Requirements và Other Requirements

### ISSUE THREAD

**Issue by VoHongKhang** [VoHongKhang/Nhom10_CCPTPM#30]
- [x]  Task 1 (ĐỨC ANH NGÀY 2): Viết Other Nonfunctional Requirements

- [x] Task 2 (ĐỨC ANH NGÀY 3): Viết Other Requirements

**Comment by ducanh1811** [comment]
Kết quả task 1 (ĐỨC ANH): (các bạn kéo xuống dưới file doc này để xem kết quả nhé): https://docs.google.com/document/d/1XVHaUNoguIhTs_ZXBmcIV_qowdq4-n4h/edit

**Comment by ducanh1811** [comment]
Kết quả task 2 (ĐỨC ANH): (các bạn kéo xuống dưới file doc này để xem kết quả làm việc của mình nhé): https://docs.google.com/document/d/1XVHaUNoguIhTs_ZXBmcIV_qowdq4-n4h/edit
