### ISSUE TITLE
Mô tả lại usercase diagram

### ISSUE THREAD

**Issue by VoHongKhang** [VoHongKhang/Nhom10_CCPTPM#32]
- [x] Task 1 (Khang): User xem lịch sử cuộc gọi
- [x] Task 2 (Khang): User xem các báo cáo và phân tích 
- [x] Task 3 (Khang): User đăng ký hoặc hủy dịch vụ đăng ký
- [x] Task 4 (Chí): User yêu cầu hỗ trợ, liên lạc với người quản lý
- [x] Task 5  (Chí): User quản lý tài khoản
- [x] Task 6  (Chí): User và admin đánh giá trải nghiệm
- [x] Task 7  (Chí): User và admin đăng nhập
- [x] Task 8 (Anh NGÀY 4): User và admin quản lý tài khoản
- [x] Task 9 (Anh NGÀY 4): Admin quản lý dịch vụ
- [x] Task 10 (Anh NGÀY 5): Admin quản lý người dùng
- [x] Task 11 (Anh NGÀY 6): Admin quản lý báo cáo và phân tích

**Comment by VoHongKhang** [comment]
Kết quả task 1:

**Comment by VoHongKhang** [comment]
Kết quả task 2:

**Comment by VoHongKhang** [comment]
Kết quả task 3:

**Comment by VoHongKhang** [comment]
Kết quả task 4

**Comment by VoHongKhang** [comment]
Kết quả task 5:

**Comment by VoHongKhang** [comment]
Kết quả task 6:

**Comment by ducanh1811** [comment]
Kết quả task 8 (ĐỨC ANH)
![image](https://user-images.githubusercontent.com/119037853/229365886-6f311381-cabb-4ac0-a216-379a4c1030d3.png)

**Comment by ducanh1811** [comment]
Kết quả task 9 (ĐỨC ANH): 
![image](https://user-images.githubusercontent.com/119037853/229365951-4bfe6ec7-4818-44a8-8dfd-9c0e856bab0f.png)

**Comment by ducanh1811** [comment]
Kết quả task 10: 
![image](https://user-images.githubusercontent.com/119037853/229366013-8a4f99cc-6e59-4045-a027-9825219c62c0.png)

**Comment by ducanh1811** [comment]
Kết quả task 11 (ĐỨC ANH): 
![image](https://user-images.githubusercontent.com/119037853/229366051-68ec1320-8d2b-450c-90fa-61f507518205.png)

**Comment by QuocChi76** [comment]
![image](https://user-images.githubusercontent.com/126311453/229421152-17d5102c-e5a9-4366-b64c-55a0f0f45f86.png)
