### ISSUE TITLE
Xây dựng kế hoạch test

### ISSUE THREAD

**Issue by VoHongKhang** [VoHongKhang/Nhom10_CCPTPM#34]
- [x] Task : Kịch bản 1: Test login
- [x] Task: tìm hiểu test tools và chọn tools phù hợp
- [x] Task: Tìm hiểu Selenium IDE cho project
- [x] Task: Cài đặt Selenium IDE và tìm hiểu sử dụng 
- [x] Task: Viết các testcase cho chức năng login
- [x] Task: Thực hiện sử dụng tool và viết các testcase trên tool

**Comment by QuocChi76** [comment]
Task1: Test login
TestCase:
- Không nhập username và Password
- Không nhập username
- không nhập password
- Username và password không đúng
- username và password đúng.
Chi tiết:

**Comment by QuocChi76** [comment]
task: tìm hiểu test tools và chọn tools phù hợp
Kết quả:
Đối với ngôn ngữ và framework nhóm lựa chọn là reactjs thì sẽ có 1 số tools  phổ biến được sử dụng để kiểm thử ứng dụng web ReactJS:

- Jest: Jest là một framework kiểm thử JavaScript mã nguồn mở phổ biến. Nó hỗ trợ việc kiểm thử các thành phần React như snapshot testing, DOM testing, và integration testing.
- Enzyme: Enzyme là một thư viện kiểm thử React được phát triển bởi Airbnb. Nó cung cấp các phương thức để kiểm thử các thành phần React như shallow rendering, full rendering và static rendering.
- Cypress: Cypress là một công cụ kiểm thử chức năng kết hợp với kiểm thử E2E (end-to-end) cho ứng dụng web. Nó cho phép bạn kiểm tra các chức năng và tính năng của ứng dụng trong môi trường trình duyệt thực.
- Selenium: Selenium là một bộ công cụ kiểm thử tự động phổ biến được sử dụng để kiểm thử các ứng dụng web. Nó hỗ trợ các ngôn ngữ lập trình như Java, Python và Ruby và cho phép kiểm thử các trình duyệt khác nhau.
- Puppeteer: Puppeteer là một thư viện Node.js được phát triển bởi Google để kiểm thử và kiểm soát các trình duyệt. Nó cung cấp một API cho việc kiểm thử các tính năng của ứng dụng web và cho phép tương tác với các thành phần của trình duyệt.

Và nhóm lựa chọn Selenium để tìm hiểu và sử dụng cho đồ án

**Comment by QuocChi76** [comment]
Task: Tìm hiểu Selenium IDE cho project:

Lý do nhóm lựa chọn Selenium IDE  vì:

- Đa nền tảng: Selenium hỗ trợ đa nền tảng bao gồm Windows, Linux và macOS.
- Tương thích với nhiều trình duyệt: Selenium hỗ trợ đa dạng các trình duyệt phổ biến như Chrome, Firefox, IE, Safari...
- Hỗ trợ nhiều ngôn ngữ lập trình: Selenium hỗ trợ các ngôn ngữ lập trình phổ biến như Java, C#, Python, Ruby...
- Tích hợp với các công cụ kiểm thử khác: Selenium có thể tích hợp với các công cụ kiểm thử khác như TestNG, JUnit, NUnit, Cucumber...
- Dễ sử dụng: Selenium có một giao diện người dùng đơn giản, dễ sử dụng và dễ học.
- Tự động hóa được các tác vụ lặp đi lặp lại: Selenium có thể tự động hóa các tác vụ lặp đi lặp lại, giúp giảm thời gian và công sức cho các nhà phát triển.

Ngoài ra tools này cũng có 1 số hạn chế nhưng nhóm sẽ tìm cách khắc phục

**Comment by QuocChi76** [comment]
Task: Cài đặt Selenium IDE

Hiện tại nhóm sử dụng extendsion Selenium ide dành cho trình duyệt chomre
Các bước thực hiện :

1. Truy cập vào Chrome Web Store tại địa chỉ: https://chrome.google.com/webstore/category/extensions.
2. Tìm kiếm "Selenium IDE" hoặc truy cập vào đường dẫn: https://chrome.google.com/webstore/detail/selenium-ide/mooikfkahbdckldjjndioackbalphokd để tải tiện ích này.
3. Nhấp vào nút "Add to Chrome" để cài đặt Selenium IDE cho trình duyệt Chrome.
4. Xác nhận việc cài đặt bằng cách nhấp vào nút "Add extension" trên hộp thoại xác nhận.
5. Sau khi cài đặt thành công, Selenium IDE sẽ xuất hiện trên thanh công cụ của trình duyệt Chrome.

**Comment by QuocChi76** [comment]
Viết các testcase cho chức năng login

**Comment by QuocChi76** [comment]
Task: Thực hiện sử dụng tool và viết các testcase trên tool
Kết quả : https://drive.google.com/file/d/15GiUK4XfEYrSYxGOs2SktivE4-ImCXcw/view?usp=sharing
