### ISSUE TITLE
Tích hợp CI/CD vào project

### ISSUE THREAD

**Issue by VoHongKhang** [VoHongKhang/Nhom10_CCPTPM#35]
- [x] Tìm hiểu CI/CD
- [x] Chọn CI/CD CircleCI cho project
- [x] Ưu nhược điểm của CircleCI

**Comment by VoHongKhang** [comment]
Kết quả 
CI/CD là viết tắt của Continuous Integration/Continuous Delivery hoặc Continuous Deployment. Đây là một quá trình tự động hóa trong phát triển phần mềm nhằm tối đa hóa chất lượng, hiệu suất và độ tin cậy của phần mềm.

Continuous Integration (CI) là quá trình tự động hóa việc kiểm tra và xây dựng mã nguồn mới khi được đưa lên kho chứa. Quá trình này đảm bảo rằng mã nguồn mới sẽ không gây ra lỗi khi hợp nhất vào mã nguồn chính.

Continuous Delivery (CD) là quá trình tự động hóa việc triển khai phần mềm từ mã nguồn đến môi trường sản xuất. Quá trình này đảm bảo rằng phần mềm được cập nhật một cách liên tục và nhanh chóng.

CircleCI là một dịch vụ CI/CD hoàn chỉnh, được sử dụng rộng rãi trong ngành công nghiệp phần mềm. CircleCI cung cấp một số tính năng tiên tiến như khả năng tùy chỉnh và cấu hình linh hoạt, tích hợp với nhiều công cụ phát triển phổ biến, khả năng chạy các bài kiểm tra tự động và phân tích kết quả đầu ra.

Để bắt đầu sử dụng CircleCI cho project của bạn, bạn có thể thực hiện các bước sau:

Đăng ký tài khoản CircleCI và đăng nhập vào trang web.

Tạo một project mới trên CircleCI và kết nối nó với kho chứa mã nguồn của bạn trên GitHub hoặc Bitbucket.

Cấu hình quy trình CI/CD của bạn bằng cách tạo một tệp cấu hình .yml trong kho chứa của bạn. CircleCI hỗ trợ nhiều ngôn ngữ lập trình và các công cụ phát triển khác nhau.

Thực hiện các bài kiểm tra tự động và triển khai phần mềm của bạn trên môi trường sản xuất bằng cách kích hoạt các quy trình CI/CD của bạn trên CircleCI.

Theo dõi các kết quả của quy trình CI/CD của bạn trên trang web CircleCI và điều chỉnh cấu hình của bạn nếu cần thiết.

Với các tính năng linh hoạt và dễ sử dụng của nó, CircleCI là một lựa chọn tốt cho các dự án phần mềm nhằm tối ưu hóa quá trình phát triển và triển khai phần mềm

**Comment by QuocChi76** [comment]
Một số ưu điểm của CircleCI bao gồm:

Đơn giản và dễ sử dụng: CircleCI rất dễ sử dụng với giao diện người dùng thân thiện và tài liệu hướng dẫn phong phú. Người dùng có thể cài đặt các dự án của mình với chỉ vài bước đơn giản.

Đa nền tảng: CircleCI có thể hỗ trợ nhiều loại dự án và các ngôn ngữ lập trình khác nhau. Bất kỳ dự án nào sử dụng Git để quản lý mã nguồn và có thể được xây dựng bằng các công cụ như Docker hoặc Vagrant đều có thể được tích hợp với CircleCI.

Tích hợp dễ dàng: CircleCI tích hợp tốt với nhiều công cụ phát triển phổ biến như GitHub, Bitbucket và GitLab. Các dự án cũng có thể được tích hợp với các công cụ khác như JIRA, Slack và HipChat.

Tốc độ xây dựng nhanh: CircleCI có thể xây dựng các dự án nhanh chóng và đồng thời chạy các bộ kiểm tra phần mềm tự động để đảm bảo rằng mã nguồn mới được tích hợp một cách hợp lý và không làm hỏng hệ thống.

Tính linh hoạt cao: CircleCI cho phép người dùng tùy chỉnh các bước xây dựng và triển khai theo nhu cầu của họ. Các pipeline có thể được thiết kế để chạy các bước xây dựng, kiểm tra và triển khai theo bất kỳ cách nào mà người dùng muốn.

Hỗ trợ 24/7: CircleCI cung cấp hỗ trợ khách hàng 24/7 thông qua email hoặc chat trực tuyến. Người dùng có thể đặt câu hỏi và nhận được trợ giúp từ các chuyên gia kỹ thuật của CircleCI trong thời gian ngắn nhất có thể.


Một số nhược điểm của CircleCI là:



Không hỗ trợ multi-cloud: CircleCI chỉ hỗ trợ chạy trên AWS và Google Cloud, không hỗ trợ các dịch vụ đám mây khác.

Hạn chế đối với customization: Mặc dù CircleCI cung cấp nhiều tính năng, nhưng việc tùy chỉnh chúng không được đầy đủ, giới hạn ở một số trường hợp.

Khó khăn khi xử lý các lỗi quá trình build: CircleCI không cung cấp các công cụ khắc phục sự cố tùy chỉnh cho quá trình build, vì vậy việc tìm kiếm và sửa chữa lỗi có thể khó khăn và tốn thời gian.

Độ ổn định: CircleCI đôi khi gặp phải sự cố về độ ổn định và hiệu suất, làm gián đoạn quá trình build và triển khai của các ứng dụng.
