### ISSUE TITLE
Tích hợp CI/CD ( circle ci) cho project 

### ISSUE THREAD

**Issue by QuocChi76** [VoHongKhang/Nhom10_CCPTPM#40]
- [x] Tích hợp circle ci cho project

**Comment by QuocChi76** [comment]
B1: cấu hình file config.xml
version: 2.1
orbs:
  docker: circleci/docker@1.1.0
jobs:
  build:
    docker:
      - image: cimg/node:17.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Test Docker
          command: docker --version
      # - run:
      #     name: Start Docker
      #     command: sudo service docker start
      - run:
          name: Install Dependencies
          command: npm install
         
      - run:
          name: Build and push Docker image
          command: |
            docker build -t vohongkhang/react-app:1.0.3 .
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
            docker push vohongkhang/react-app:1.0.3
         
workflows:
  build-and-deploy:
    jobs:
      - build


B2:Qua circle ci bấm
![image](https://user-images.githubusercontent.com/126311453/234206709-5f017578-80e4-454a-a179-9fab5b8b1d73.png)

B3: Chọn 
![image](https://user-images.githubusercontent.com/126311453/234206781-8f8acf59-0996-49ff-940a-c59289d6275c.png)

B4: 
![image](https://user-images.githubusercontent.com/126311453/234206862-fbfac814-e4e8-4ef2-a85d-9f6e324f3394.png)
B5:Dán file config vào đây và nhấn commit and run
![image](https://user-images.githubusercontent.com/126311453/234206960-0eb6495b-8ab0-4986-8bb2-3a54254344e9.png)

Thành công
![image](https://user-images.githubusercontent.com/126311453/234207053-f5007eb3-f490-44af-8cfe-33aeaa29a078.png)

**Comment by 1905QuocChi** [comment]
Kết quả môn này như nào vậy a
